### ISSUE TITLE
$scope.$watch is not a function in 0.13 ?

### ISSUE THREAD

**Issue by KINKCreative** [lega911/angular-light#234]
Title says it all. I seem to have trouble using $watch, basically a piece of code that worked. I noticed I am running 0.13. It does work with 0.12.30 so I am curious if there's a breaking change.

e.g
`$scope.$watch('query', function(newValue) { console.log(newValue)});`

**Comment by lega911** [comment]
0.13 has $watch (which uses ChangeDetector.watch), example https://jsfiddle.net/lega911/ubgv96ce/
the biggest change in 0.13, there are no local variables from al-repeat in scope, they are available via $getValue and declarative binding.

0.14 doesn't have scope and $watch, it uses ChangeDetector.watch directly.
